### ISSUE TITLE
[Statuttforslag]Forby saksofoner i motstanden

### ISSUE THREAD

**Issue by SiviKiwi** [Motstanden/motstandens-statutter#20]
Saksofoner har blitt en pest og en plage på øvelser. Saksofonister tenker for høyt om seg selv og de stjeler oppmerksomheten fra resten av orchesteret. For å verne om motstanderes mentale og fysiske helse, samt å sørge for at alle innstrumenter får sin tid i lyset, må saksofoner forbys.

**Comment by Torsteinws** [comment]
Avvist
