### ISSUE TITLE
[Statuttforslag]Alle i motstanden skal ha med munnspill i lomma som sekundærinstrument

### ISSUE THREAD

**Issue by johnal18** [Motstanden/motstandens-statutter#23]

**Comment by SiviKiwi** [comment]
Evt. Ha et lite innstrument som passer i lomma. Ikke nødvendigvis munnspill

**Comment by Torsteinws** [comment]
For å ikke skape konflikt med #22 så foreslår jeg å legge til underpunktet: 
 - Denne paragrafen gjelder ikke for Sivert Lauvdal – Den Grønne Messias.

**Comment by Torsteinws** [comment]
Avvist
