### ISSUE TITLE
Ikke lov å låne bort hodeplagg

### ISSUE THREAD

**Issue by Ninatgun** [Motstanden/motstandens-statutter#30]
Andre stjeler og låner hodeplagg for gøy på fylla og ellers hele tiden. Dette resulterer i stress og tapt Hodeplagg. Foreslår derfor at hodeplagget er privat uten mulighet for utlån. Så slipper man å føle seg frekk når man ikke vil låne bort, man kan si det man faktisk ikke har lov.

**Comment by Torsteinws** [comment]
#
Duplicate of #24
