### ISSUE TITLE
[Diskusjon] Habilitetsklausuler for medlemmer som er med i andre orchestre

### ISSUE THREAD

**Issue by Torsteinws** [Motstanden/motstandens-statutter#42]
Burde vi ha noen habilitetsklausuler i statuttene med tanke på at vi har en del ohmlause medlemmer i Motstanden? 
Med ohmlause medlemmer så tenker jeg på medlemmer som prioriterer Dei Taktlause over Motstanden.

For eksempel så risikerer Motstanden i teorien at:
- Dei Taktlause kan kuppe Motstanden ved å starte en ekstraordinær generalvorssamling.
- Statuttendringer som er bra for Motstanden kan enkelt bli blokkert ettersom vi krever **overkvalifisert flertall** for å gjøre endringer.
For eksempel: Hva om vi ønsker å statuttfeste at Ohma Electra er en trikk?

Er veldig usikker på hvordan dette skal funke. Det er jo også utrolig viktig å ikke diskriminere dei ohmlause!

**Comment by Pine-Land** [comment]
Jeg synes ting som beskytter oss mot utro medlemmer er helt greit. At de mister stemmeretten hvis det kan vises til grov skjevfordeling mellom oppmøte. For eksempel 8 taktløse øvinger til 1 motstand øvelse er nokk til å miste stemmerett ved nærmeste valg

**Comment by jorgenrb** [comment]
Peak

**Comment by raflemakt** [comment]
duplikat. #47
