### ISSUE TITLE
[Meta] Hvilken lisens burde dette prosjektet ha?

### ISSUE THREAD

**Issue by Torsteinws** [Motstanden/motstandens-statutter#43]
Føler ikke helt [MÅKESODD V1](https://motstanden.no/lisens) er riktig lisens å bruke her

**Comment by raflemakt** [comment]
Studentorchesteret den Ohmske Motstanden ble  på sin femte (5.) generalvorsamling enige om å gi Torsteinws eller Motstandens styre fullmakt til å velge hvilken lisens som skal brukes på repositoriet "motstanden-statutter".
