### ISSUE TITLE
[Statuttendring] Fjerne krav om elektramedlemskap

### ISSUE THREAD

**Issue by SiviKiwi** [Motstanden/motstandens-statutter#44]
Det er mye å kreve av eksterne å betale 450kr for å bli med. Vi reklamerer ikke for eksterne, men de som vil bli med burde få lov.

**Comment by Pine-Land** [comment]
Så lenge motstanden bruker Elektra sitt lager og kontor er det rettferdig at man må være medlem i Elektra. Hvis vi skal fjerne dette krevet bør vi skille oss helt ut og ikke lenger bruke noe av Elektra

**Comment by Torsteinws** [comment]
Jeg tenker at kravet generelt sett skader Motstanden, noe Elektra er lite tjent med.

Elektra vil jo fortsatt være vår identitet og målgruppe. Å fjerne kravet vil jo ikke endre det.

**Comment by jorgenrb** [comment]
Elektra bad

**Comment by jorgenrb** [comment]
Elektra bøyer seg i støvet til Motstanden

**Comment by jorgenrb** [comment]
Ahem, fuck, Elektra

**Comment by raflemakt** [comment]
>; ( >~
