### ISSUE TITLE
[Statuttforslag] Elektrastyret må skrive kontrakt ved overtakelse av midler

### ISSUE THREAD

**Issue by Torsteinws** [Motstanden/motstandens-statutter#45]
I statuttene våre står det at dersom Motstanden oppløses skal midlene våres fryses og forvaltes av Elektra i 20 år.
I Elektra sine vedtekter står det at de bare skal fryses og forvaltes i 5 år. 

For å sikre at midlene våre faktisk blir fryst i 20 år burde vi legge til noe i følgende dur:

Før Elektra overtar Motstandens midler må Elektrastyret skrive kontrakt på at de vil holde midlene fryst i 20 år.
Dersom Elektrastyret ikke ønsker å skrive denne kontrakten, kan tidligere alumni i Motstanden påberope seg forvaltningsrett for midlene.
Videre, dersom ingen alumni i Motstanden påberoper seg forvaltningsrett, så faller retten tilbake igjen til Elektra.

**Comment by Torsteinws** [comment]
Relatert til #18

**Comment by Torsteinws** [comment]
Hvis vi ønsker denne endringen burde vi også definere hvem som skal signere kontrakten, og hva vi mener med alumni i Motstanden.

**Comment by raflemakt** [comment]
Studentorchesteret den Ohmske Motstanden (heretter Motstanden) har (etter lang og saklig diskusjon) stemt over dette forslaget ved sin femte generalvorsamling den tjugeåttende oktober 2023 og kommet fram til at dette statuttvedtaket vedtas og skal innlemmes i Motstandens statutter.
