### ISSUE TITLE
Tilhørighet 

### ISSUE THREAD

**Issue by Ninatgun** [Motstanden/motstandens-statutter#48]
2.1.1 Motstanden er en interessegruppe underlagt Linjeforeningen Elektra.

Endres til 

2.1.1 Motstanden er en organisasjon som fungerer som en egen interessegruppe innad i Linjeforeningen Elektra.

**Comment by jorgenrb** [comment]
Bra

**Comment by raflemakt** [comment]
Forslaget vedtas
