### ISSUE TITLE
[Endring] Endringsansvarlig

### ISSUE THREAD

**Issue by SiviKiwi** [Motstanden/motstandens-statutter#58]
Få inn i protokollene at det velgens en person til å ha ansvar for å putte nye statutter og endringer inn i latexdokumentet.

**Comment by Torsteinws** [comment]
Vil bare meddele at dette har tradisjonelt sett vært webingeniør sitt ansvar.

**Comment by SiviKiwi** [comment]
nytt paragraf: Etter statuttendringer velges det en latexendringoppdateringsansvarligingeniør som står ansvarlig for å oppdatere endringene i latexdokumentet innen neste genvors. 

vedtatt
