### ISSUE TITLE
[Endring]

### ISSUE THREAD

**Issue by SiviKiwi** [Motstanden/motstandens-statutter#62]
Opprette en legendestilling som som webingeniør vil tilhøre Torstein. Fram til han sier fra seg stillingenen.

**Comment by ElektroMannen** [comment]
Titelen skal endres til legenden om webgiveren, web skaperen Torstein eller en tittel og ikkje en posisjon som ingeniør

**Comment by ElektroMannen** [comment]
Titelen kan endres til legenden om webgiveren, web skaperen Torstein eller en tittel og ikkje en posisjon som ingeniør

**Comment by SiviKiwi** [comment]
paragraf 5.1.1 5. webingeniør: legenden Torstein Wilhelmsen Sandvik 

paragraf 5.5 En legende kan når som helst si fra seg stillingen, stillingen kan da fylles av en dødelig.

Vedtatt

**Comment by Torsteinws** [comment]
Hahahahaha 😂💀⚰️
